---
- name: Ansible playbook to copy a file
  hosts: all
  become: true
  tasks:
  - name: copy file to remote location
    copy:
      src: /opt/ansible/index.html
      dest: /home/ansadmin
      mode: 0600
      owner: John

