---
- name: This playbook installs and starts httpd
  hosts: webservers
  become: true
  tasks:
  - name: install packages
    yum:
      name: httpd
      state: installed

  - name: Start httpd service
    service:
      name: httpd
      state: started

