---
- name: setup tomcat
  hosts: all
  become: true
  tasks:
  - name: Install Java
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: Install Java on Ubuntu
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"
 
  - name: download tomcat
    get_url:
      url: https://mirror.nodesdirect.com/apache/tomcat/tomcat-8/v8.5.66/bin/apache-tomcat-8.5.66.tar.gz
      dest: /opt

  - name: untar apache packages
    unarchive:
      src: /opt/apache-tomcat-8.5.66.tar.gz
      dest:  /opt
      remote_src: yes

  - name: add execution permission on startup.sh 
    file:
      path: /opt/apache-tomcat-8.5.66/bin/startup.sh
      mode: 0777

  - name: start tomcat services
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.66/bin


