---
- name: This playbook stops and uninstall httpd service
  hosts: webservers
  become: true
  tasks:
  - name: Stop httpd service
    service: 
      name: httpd
      state: stopped

  - name: Uninstall httpd service
    yum:
      name: httpd
      state: removed

